### ISSUE TITLE
Standalone?

### ISSUE THREAD

**Issue by davidchase** [GBKS/Wookmark-jQuery#172]
Any thoughts on a jquery-less version of this plugin?

-D

**Comment by ram-you** [comment]
Hi,
Some news about the javascript-vanilla version ?
Thank you.

**Comment by Sebobo** [comment]
Didn't have a lot of time at the end of last year, but I started some days ago again.
Big rewrite, so a lot of stuff needs to be done.

**Comment by Sebobo** [comment]
I'm getting closer to the 2.0 release. 
You can checkout the `nojquery` branch and try it. Just pushed a few commits.

Whats left is mainly testing, fixing placeholders and updating the readme and examples. Hope I can get that done fast.

**Comment by Sebobo** [comment]
Done :)
