### ISSUE TITLE
assign random height.

### ISSUE THREAD

**Issue by ctf0** [GBKS/Wookmark-jQuery#182]
is there away for the plugin to assign random height to the items ,the reason am asking because the items on the wookmark have random heights and i wanted to do that same in my app but currently i don't know how.

**Comment by Sebobo** [comment]
The plugin doesn't do that, it's only the small inline example script to show how Wookmark adapts. 
And what are you trying to do this way?

**Comment by ctf0** [comment]
i have some posts that have different images of different heights ,and the only way i could achieve what i want is by adding the post title right after the image ,
and thats why i asked about using the plugin to assign some randomness ,
exactly the same way u do in the example when u click on any of the images but instead the plugin will now do that when gets loaded. :)
