### ISSUE TITLE
bower_component

### ISSUE THREAD

**Issue by sutiyonodoang** [GBKS/Wookmark-jQuery#187]
Dear admin,

I've to try this web example on local server, but there is an error like 
bower_components/requirejs/require.js -- in error 404.

this mean that files are empty.
i've search on unzip file/folder but its none.
can you send me that folder (bower_components/)?

thanks in advanced,
tiyo

**Comment by Sebobo** [comment]
Hi,

you get the bower_components by installing bower with npm and running `bower install`

**Comment by sutiyonodoang** [comment]
ooo, ok
I'll try it.

thx
