### ISSUE TITLE
mysql data load

### ISSUE THREAD

**Issue by sutiyonodoang** [GBKS/Wookmark-jQuery#191]
Dear All,

There is an example api to load image from mysql?

thx in advance

**Comment by Sebobo** [comment]
There is an example php script in `example-api` on how to create a super simple server.
You just have to replace the static `$data` part with your own code to get the data from your db.
We cannot provide that.

**Comment by sutiyonodoang** [comment]
How about dynamic data load?
Date: Tue, 21 Apr 2015 13:56:44 -0700

**Comment by Sebobo** [comment]
That's what you have to provide yourself.

**Comment by sutiyonodoang** [comment]
Ok, thx
:)
Date: Wed, 22 Apr 2015 09:38:47 -0700
